"""Deploy helper for the Gateway inventory schema.

The Labels project has no way to run DDL from a script. Direct Postgres is
dead (the pooler password in scripts/add_fulfilment_col.js was rotated and now
fails authentication) and PostgREST exposes no exec_sql RPC, so the migration
has to be pasted into the Supabase SQL Editor by a human. This does the two
things a script still can:

    python features/gateway/db/apply.py --bundle   # one file to paste
    python features/gateway/db/apply.py --verify   # did it land?

--verify checks every table, view and function over PostgREST with the service
key, so it reports the real state of the database rather than what the .sql
files say should be there.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
FILES = ["001_gateway_inventory.sql", "002_gateway_logic.sql", "003_gateway_import.sql"]
BUNDLE = os.path.join(HERE, "_apply_all.generated.sql")

TABLES = [
    "gateway_settings", "gateway_shelves", "gateway_import_batches", "gateway_import_issues",
    "gateway_lots", "gateway_transfers", "gateway_transfer_lines",
    "gateway_transfer_allocations", "gateway_movements", "gateway_recon_issues",
    "gateway_audit_log",
]
VIEWS = ["gateway_v_lots", "gateway_v_sku_balance", "gateway_v_reconciliation", "gateway_v_transfers"]
FUNCTIONS = [
    ("gateway_resolve_sku",           {"p_sku": "R6052-WH-TRI"}),
    ("gateway_fifo_sort_date",        {"p_received": "2026-01-01"}),
    ("gateway_fifo_queue",            {"p_sku": "R6052-WH-TRI"}),
    ("gateway_next_transfer_no",      {}),
    ("gateway_create_lot",            None),
    ("gateway_allocate_line",         None),
    ("gateway_allocate_override",     None),
    ("gateway_cancel_transfer",       None),
    ("gateway_post_transfer",         None),
    ("gateway_adjust_lot",            None),
    ("gateway_reverse_transfer_line", None),
    ("gateway_refresh_fifo_flag",     None),
    ("gateway_import_lot_ledger",     None),
    ("gateway_rollback_import",       None),
    ("gateway_refresh_reconciliation", None),
    ("gateway_resolve_recon_issue",   None),
]


def env() -> tuple[str, str]:
    e = {}
    p = os.path.join(REPO, ".env")
    if os.path.exists(p):
        for line in open(p, encoding="utf8"):
            m = re.match(r"\s*([A-Z0-9_]+)\s*=\s*(.*)", line)
            if m:
                e[m.group(1)] = m.group(2).strip().strip('"').strip("'")
    url = os.environ.get("SUPABASE_URL") or e.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_SERVICE_KEY") or e.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        sys.exit("SUPABASE_URL / SUPABASE_SERVICE_KEY not found")
    return url.rstrip("/"), key


def get(url: str, key: str, path: str):
    req = urllib.request.Request(url + path)
    req.add_header("apikey", key)
    req.add_header("Authorization", f"Bearer {key}")
    try:
        with urllib.request.urlopen(req, timeout=45) as r:
            return r.status, json.loads(r.read().decode() or "null")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode()[:200]


def bundle() -> None:
    parts = [
        "-- ===================================================================",
        "-- Gateway Inventory — full schema, generated by features/gateway/db/apply.py",
        "-- Paste this whole file into the Supabase SQL Editor and run it.",
        "-- Idempotent: safe to run more than once.",
        "-- ===================================================================",
        "",
    ]
    for f in FILES:
        parts.append(f"\n-- ══════════ {f} ══════════\n")
        parts.append(open(os.path.join(HERE, f), encoding="utf8").read())
    open(BUNDLE, "w", encoding="utf8").write("\n".join(parts))
    n = sum(1 for _ in open(BUNDLE, encoding="utf8"))
    print(f"wrote {BUNDLE}  ({n:,} lines)")
    print("\nNext:")
    print("  1. Supabase Dashboard -> SQL Editor -> New query")
    print(f"  2. Paste the contents of {os.path.relpath(BUNDLE, REPO)}")
    print("  3. Run")
    print("  4. python features/gateway/db/apply.py --verify")


def verify() -> int:
    url, key = env()
    bad = 0

    print("\nTables")
    for t in TABLES:
        st, body = get(url, key, f"/rest/v1/{t}?select=*&limit=1")
        if st == 200:
            _, cnt = get(url, key, f"/rest/v1/{t}?select=*&limit=1&offset=0")
            print(f"  ok    {t}")
        else:
            bad += 1
            print(f"  MISS  {t}  ({st}) {body if isinstance(body, str) else ''}")

    print("\nViews")
    for v in VIEWS:
        st, body = get(url, key, f"/rest/v1/{v}?select=*&limit=1")
        print(f"  {'ok   ' if st == 200 else 'MISS '} {v}" + ("" if st == 200 else f"  ({st})"))
        bad += st != 200

    print("\nFunctions")
    for name, args in FUNCTIONS:
        # A function with no safe arguments is probed by calling it wrong: a
        # missing function answers 404, a present one answers 400/404-with-a
        # -different-code. PostgREST reports an unknown function as PGRST202.
        path = f"/rest/v1/rpc/{name}"
        if args is None:
            st, body = get(url, key, path)
            present = not (isinstance(body, str) and "PGRST202" in body)
        else:
            qs = urllib.parse.urlencode({k: str(v) for k, v in args.items()})
            st, body = get(url, key, f"{path}?{qs}")
            present = st == 200 or not (isinstance(body, str) and "PGRST202" in body)
        print(f"  {'ok   ' if present else 'MISS '} {name}")
        bad += not present

    print("\nData")
    for t, label in [("gateway_shelves", "shelves"), ("gateway_lots", "lots"),
                     ("gateway_movements", "movements"), ("gateway_transfers", "transfers")]:
        req = urllib.request.Request(f"{url}/rest/v1/{t}?select=id&limit=1")
        req.add_header("apikey", key)
        req.add_header("Authorization", f"Bearer {key}")
        req.add_header("Prefer", "count=exact")
        req.add_header("Range", "0-0")
        try:
            with urllib.request.urlopen(req, timeout=45) as r:
                total = (r.headers.get("Content-Range") or "*/?").split("/")[-1]
                print(f"  {label:<12} {total}")
        except urllib.error.HTTPError:
            print(f"  {label:<12} —")

    print()
    if bad:
        print(f"{bad} object(s) missing — the migration has not been applied (or only partly).")
        print("Run:  python features/gateway/db/apply.py --bundle")
    else:
        print("Schema is deployed.")
        print("Next:  python features/gateway/import/import_gateway_history.py --dry-run")
    return 1 if bad else 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", action="store_true", help="write one paste-ready .sql")
    ap.add_argument("--verify", action="store_true", help="check what is actually deployed")
    a = ap.parse_args()
    if a.bundle:
        bundle()
    if a.verify:
        sys.exit(verify())
    if not (a.bundle or a.verify):
        ap.print_help()
